languages = {
	check = "english"
	skip = "spanish"
	skip = "german"
	skip = "korean"
	skip = "russian"
	skip = "simp_chinese"
	skip = "french"
}

filter = {
	show_vanilla = no
	show_loaded_mods = no

	trigger = {
		NOR = {
			#key = brace-placement
			#key = duplicate-character
			#key = duplicate-field
			#key = duplicate-item
			#key = exact-duplicate-item
			key = localization
			#key = logic
			key = missing-localization
			#key = missing-item
			#key = missing-sound
			#key = rivers
			#key = strict-scopes
			#key = structure
			#key = tooltip
		}
	}
}
